DROP TABLE IF EXISTS LIBRARY.BOOK;
DROP TABLE IF EXISTS LIBRARY.EDITORIAL;
DROP TABLE IF EXISTS LIBRARY.GENRE;
DROP TABLE IF EXISTS LIBRARY.AUTHOR;


CREATE TABLE LIBRARY.BOOK (
  ID_BOOK BIGINT  PRIMARY KEY NOT NULL,
  ID_GENRE BIGINT NOT NULL,
  ID_EDITORIAL BIGINT NOT NULL,  
  ID_AUTHOR BIGINT NOT NULL,
  TITLE VARCHAR(4000) NOT NULL,
  PRICE DECIMAL(10,4) NOT NULL,
  DATE_PUBLICATION DATE NOT NULL
);

CREATE TABLE LIBRARY.EDITORIAL (
  ID_EDITORIAL BIGINT PRIMARY KEY NOT NULL,
  NAME_EDITORIAL VARCHAR(100) NOT NULL 
);

CREATE TABLE LIBRARY.GENRE (
  ID_GENRE BIGINT PRIMARY KEY NOT NULL,
  DESCRIPTION VARCHAR(100) NOT NULL
);

CREATE TABLE LIBRARY.AUTHOR (
  ID_AUTHOR BIGINT PRIMARY KEY NOT NULL,
  NAME_AUTHOR VARCHAR(100) NOT NULL
);

ALTER TABLE LIBRARY.BOOK ADD CONSTRAINT FK_ID_GENRE
FOREIGN KEY (ID_GENRE) REFERENCES LIBRARY.GENRE(ID_GENRE);

ALTER TABLE LIBRARY.BOOK ADD CONSTRAINT FK_ID_EDITORIAL
FOREIGN KEY (ID_EDITORIAL) REFERENCES LIBRARY.EDITORIAL(ID_EDITORIAL);

ALTER TABLE LIBRARY.BOOK ADD CONSTRAINT FK_ID_AUTHOR
FOREIGN KEY (ID_AUTHOR) REFERENCES LIBRARY.AUTHOR(ID_AUTHOR);

